[build]
builder = "nixpacks"
buildCommand = "chmod +x gradlew && ./gradlew build"

[deploy]
startCommand = "java -jar build/libs/*.jar"
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
JAVA_VERSION = "21"